### ISSUE TITLE
which client do i need use ? 

### ISSUE THREAD

**Issue by leeqiufeng** [Chronicle20/gms-83-dll#10]
original or hendi's client ?

**Comment by Chronicle20** [comment]
The goal of this effort was to enable the use of the vanilla (original) client. 

That being said, you can use this over-top of another localhost. It will just be important to understand which "edits" will be compatible or even necessary with the localhost you're using.  ie. You won't need the "bypass" or "redirect" "edits" with Hendis, because that is already taken care of in the executable.
